name: C build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ex01

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run test
        run: make test

      - name: Run executable
        run: make run

      - name: Clean
        run: make clean
